Remove engines from package.json
IBM/message-catalog-manager pull request #23
Opened 2021-01-15 11:12 UTC by sharathmuthu6

When we try do npm install on our projects with node 14
```
npm WARN notsup Unsupported engine for @ibm-app-connect/loopback-connector-provider-library@1.0.200: wanted: {"node":"10","npm":"6"} (current: {"node":"14.15.1","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @ibm-app-connect/loopback-connector-provider-library@1.0.200
```

We are hitting this warning. engines will be mentioned at the application level, hence removing engines from this library.!

2021-01-15 12:00 UTC, Grahahax requested changes
Given we have never supported earlier versions I think specifying a version greater than 4.4 would be the better option here. Also would you like to add 14 to the travis build?

2021-01-19 10:59 UTC, Grahahax approved these changes

2021-01-20 05:50 UTC, srihakum commented
@Grahahax Thanks for reviewing the PR. Now this PR enables travis for Node 14 while Node 4.4 is failing. There is no code changes for older version to fail. So I believe master version itself is not built for quite long time. In this case I see 2 options
1. Increment the major version to support Node 14 and deprecate 4.4 as the runtime itself out of support.
2. Fix the master to get it working with older versions (4.4).
I would prefer Option 1 let us know your thoughts we could modify the PR soon.

2021-06-29 13:14 UTC, Grahahax commented
@srihakum this PR is still failing and open. Do you want to fix the failure or should I close this PR?

2022-11-16 17:00 UTC, mattbaileyuk commented
This has been superseded by other PRs, and the engines limit is now removed.

2022-11-16 17:00 UTC, closed without merging